# Generated by Django 5.1 on 2024-09-02 17:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_commented_by_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pfp'),
        ),
    ]
